apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-v2-deployment
  labels:
    app: portfolio-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-v2
  template:
    metadata:
      labels:
        app: portfolio-v2
    spec:
      containers:
        - name: portfolio-v2
          image: kristienn/portfolio-v2
          ports:
            - containerPort: 80

