apiVersion: v1
kind: Service
metadata:
  name: portfolio-v2-service
spec:
  type: NodePort
  selector:
    app: portfolio-v2
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
      nodePort: 30100
