name: Main

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: "Publish"
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      REGISTRY_NAME: registry.digitalocean.com/kristien-docr

    steps:
      - uses: actions/checkout@v4

      - name: setup doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: authenticate
        run: doctl registry login --expiry-seconds 1200

      - name: publish app
        run: |
          docker build -t portfolio-v2 .
          docker tag portfolio-v2 $REGISTRY_NAME/portfolio-v2:latest
          docker push $REGISTRY_NAME/portfolio-v2:latest

      - name: publish nginx-lb
        run: |
          docker build -t portfolio-v2-nlb-proxy ./nginx
          docker tag portfolio-v2-nlb-proxy $REGISTRY_NAME/portfolio-v2-nlb-proxy:latest
          docker push $REGISTRY_NAME/portfolio-v2-nlb-proxy:latest
