name: Main

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: "Publish"
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      REGISTRY_NAME: registry.digitalocean.com/kristien-docr

    steps:
      - uses: actions/checkout@v4

      - name: setup doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: docr login
        run: doctl registry login --expiry-seconds 1200

      - name: build
        run: docker build -t portfolio-v2 .

      - name: tag
        run: docker tag portfolio-v2 $REGISTRY_NAME/portfolio-v2:$(echo $GITHUB_SHA | head -c7)

      - name: push
        run: docker push $REGISTRY_NAME/portfolio-v2:$(echo $GITHUB_SHA | head -c7)
