name: Main

on:
  push:
    branches:
      - main

jobs:
  build:
    name: "Publish"
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      REGISTRY_NAME: registry.digitalocean.com/kristien-docr

    steps:
      - uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DOCR
        run: doctl registry login --expiry-seconds 1200

      - name: Push to DOCR
        run: docker push $REGISTRY_NAME/portfolio-v2:$(echo $GITHUB_SHA | head -c7)
