name: Main

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: "Publish"
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      REGISTRY_NAME: registry.digitalocean.com/kristien-docr
    needs: [ build ]

    steps:
      - uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DOCR
        run: doctl registry login --expiry-seconds 1200

      - name: Build image
        run: docker build -t portfolio-v2 .

      - name: Tag image
        run: docker tag docker tag portfolio-v2 $REGISTRY_NAME/portfolio-v2:$(echo $GITHUB_SHA | head -c7)

      - name: Push to DOCR
        run: docker push $REGISTRY_NAME/portfolio-v2:$(echo $GITHUB_SHA | head -c7)
